motivational = ['"Perfection Is Procrastination Masquerading as Quality Control" - Chris Williamson',
                '"This is what hard feels like, and that\'s okay" - Alex Hormozi', 
                '"The only way to do great work is to love what you do" - Steve Jobs',
                '"You miss 100% of the shots you don\'t take" - Wayne Gretzky',
                '"The best revenge is massive success" - Frank Sinatra',
                "You don't lack time, you lack priority.",
                "Discipline is doing what your future self will thank you for.",
                "Comfort is the fastest way to mediocrity.",
                "Motivation starts you, discipline finishes you.",
                "If it’s easy, it’s probably not changing you.",
                "You already know what to do—you’re just avoiding it.",
                "Your habits are your real identity.",
                "Results don’t care about your excuses.",
                "The life you want requires a version of you that doesn’t exist yet.",
                "Weak decisions compound just like strong ones.",

                "Every distraction is a trade—you’re giving up something better.",
                "You can’t outthink a life you refuse to act on.",
                "Consistency beats intensity every time.",
                "You’re not stuck—you’re just comfortable.",
                "Fear grows when you delay action.",
                "Action shrinks anxiety.",
                "You become what you repeatedly tolerate.",
                "Hard choices now create easy lives later.",
                "Easy choices now create hard lives later.",
                "Nobody is coming to fix your life.",

                "Your potential means nothing without execution.",
                "Stop negotiating with your laziness.",
                "You don’t need more information—you need more action.",
                "Progress is built on boring repetition.",
                "Discipline is self-respect in action.",
                "You either control your day or your day controls you.",
                "If you avoid pain, you avoid growth.",
                "Most people quit right before things get good.",
                "You can’t build a strong life with weak habits.",
                "Small wins stack into big outcomes.",

                "Your environment shapes your behavior—choose it wisely.",
                "Excuses sound best to the person making them.",
                "You’re always training yourself—either for success or failure.",
                "Focus is a superpower in a distracted world.",
                "The more you delay, the harder it gets.",
                "Success is mostly showing up when you don’t feel like it.",
                "You don’t rise to your goals—you fall to your systems.",
                "Pain is temporary, regret lasts longer.",
                "Discipline feels hard now, regret feels worse later.",
                "Your future is hidden in your daily routine.",

                "If it doesn’t challenge you, it won’t change you.",
                "Growth requires discomfort—there’s no way around it.",
                "You can’t skip the process and still expect the result.",
                "Time will pass anyway—use it or waste it.",
                "You are what you repeatedly do, not what you plan.",
                "Waiting for the perfect moment is procrastination in disguise.",
                "The standard you walk past is the standard you accept.",
                "You don’t need to feel ready—you need to start.",
                "Most people fail because they stop, not because they can’t.",
                "Your excuses are killing your potential.",

                "Effort over ego.",
                "Build discipline before chasing motivation.",
                "If you’re not improving, you’re declining.",
                "You can’t cheat consistency.",
                "Show up tired, show up anyway.",
                "Success is built in the unseen hours.",
                "You’re one decision away from a different path.",
                "Stop chasing comfort—start chasing growth.",
                "You don’t need more time—you need more focus.",
                "The work you avoid is the work you need.",

                "Winners do what losers avoid.",
                "Comfort now, pain later—or pain now, growth later. Choose.",
                "Every day is a vote for the person you become.",
                "If you don’t build discipline, life will build it for you.",
                "You either sacrifice for your goals or your goals get sacrificed.",
                "Talent is nothing without consistency.",
                "Discipline is choosing what you want most over what you want now.",
                "Stop scrolling your life away.",
                "You can waste years being comfortable.",
                "Growth begins where excuses end.",

                "The grind is where you earn your confidence.",
                "You don’t get confidence first—you build it through action.",
                "Your comfort zone is a slow death.",
                "Action creates clarity, not the other way around.",
                "You don’t need a new plan—you need commitment.",
                "Do the hard thing first.",
                "If it’s important, you’ll make time.",
                "If not, you’ll make excuses.",
                "Results follow habits, not hype.",
                "The difference is consistency, not intelligence.",

                "You can’t stay the same and expect change.",
                "You owe yourself discipline.",
                "Nobody cares—work harder.",
                "Success is boring, repetitive, and predictable.",
                "Master the basics relentlessly.",
                "Your phone is stealing your future.",
                "Focus on execution, not perfection.",
                "The longer you wait, the further you fall behind.",
                "You’re capable of more than your current standards.",
                "Raise your standards or lower your expectations.",

                "Discipline is freedom.",
                "The hard path leads to an easy life.",
                "Stop thinking, start doing.",
                "You don’t find time—you create it.",
                "If you want different results, act differently.",
                "Your habits are either building you or breaking you.",
                "Success leaves clues—follow them.",
                "Be harder on yourself than life has to be.",
                "The work always shows.",
                "Start now, adjust later."]

philosophical = ['"Thinking is difficult, that\'s why most people judge" - Carl Jung',
                 '"You are what you do, not what you say you will do" - Carl Jung',
                 '"In the middle of every difficulty lies opportunity" - Albert Einstein',
                 '"The greatest glory in living, lies not in falling, but in rising every time we fall" - Nelson Mandela',
                 '"Don\'t be pushed around by the fears in your mind. Be lead by the dreams in your heart" - Roy T. Bennett',
                 ]

love = ['"I would recognise you in total darkness, were you mute and I deaf. I would recognise you in another lifetime entirely, in different bodies, different times. And I would love you in all of this, until the very last star in the sky burnt out into oblivion" - Achilles',
        '"I\'d recognise him by touch alone, by smell. I\'d know him blind, by the way his breaths came and his feet struck the sand. I\'d know him in death, at the end of the world" - Patroclus',
        '"Any moment might be our last. Everything is more beautiful because we\'re doomed. You will never be lovelier than you are now. We will never be here again" - Achilles',
        '"I remember looking up into the night sky and begging the wishing star for someone who would stay with me for love. But the wishing star did not give me anybody. Rather she descended from the heavens herself and turned into you" - Unknown']

genres = ['motivational', 'philosophical', 'love']